export const ErrorCodes = {
  USER_EXISTS: "USER_EXISTS",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  USER_BLOCKED: "USER_BLOCKED",
  FORBIDDEN: "FORBIDDEN",
  USER_NOTFOUND: "USER_NOTFOUND",
};

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
